### ISSUE TITLE
Unable to Reun QT wallet on Ubuntu 18.4

### ISSUE THREAD

**Issue by waterfallm** [CCYofficial/CCY#1]
When trying to run wallet on ubuntu 18.04 desktop i get the error

"error while loading shared libraries: libprotobuf.so.9"
I'm unable to get this version from std ubuntu repositoroies

**Comment by CCYofficial** [comment]
First try:
sudo ldconfig
or
export LD_LIBRARY_PATH=/usr/local/lib

Here are libs if you are missing some of them https://github.com/CCYofficial/CCY/releases/download/1.2.1.0/libs.zip . Unzip them to /usr/lib

**Comment by waterfallm** [comment]
Fab i'll try shortly and get back to you.

**Comment by waterfallm** [comment]
Great it worked i must of missed the libs.zip in the release.

**Comment by CCYofficial** [comment]
That Ubuntu 18.04 binary was compiled with older protobuf version - I recompiled it with libprotobuf.so.10 so it should work with default Ubuntu 18.04 protobuf version now.
